# Site settings
title: KomeCafe
SEOTitle: Kome Cafe Rang Xay Nguyên Chất
header-img: img/home-bg.jpg
email: cafe@kome.top
description: "Kome Café chuyên cung cấp Cafe Rang Xay Nguyên Chất cho các quán coffee tại Hà Nội. Cà phê nguyên chất 100% rang mộc sạch, túi thơm cafe ô tô, hộp quà cao cấp"
keyword: "KomeCafe, Kome Cafe, Kome, Cà Phê Rang Xay Nguyên Chất, Cà Phê Nguyên Chất, Cà Phê Rang Xay, Cà Phê Mộc, túi thơm Cafe, mặt nạ cà phê, cà phê bột, cà phê hạt"
url: "https://kome.cafe"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    KomeCafe
twitter_username:   KomeCafe
facebook_username:  KomeCaphe
linkedin_username:  komecafe



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: VN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hoangdacviet

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-29392399-7'            # Format: UA-xxxxxx-xx
ga_domain: kome.cafe



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hoang Dac Viet <br>Web Design Mobile App Marketing Startup Smarthome IoT ❤️ Love People and Cloud ❤️ NO PAIN NO GAIN."
sidebar-avatar: /img/favicon.ico      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "VnTim",
    #     href: "http://vntim.blogspot.com/"
    # },{
        title: "Kami",
        href: "https://kami.vn/"
    },{
        title: "Ống Gió Đức Tín",
        href: "https://onggioductin.com/"
    },{
        title: "Hợp Đại Thành",
        href: "https://hopdaithanh.com"
    },{
        title: "Ống Gió Tân Thành",
        href: "https://onggiotanthanh.com/"
    },{
        title: "Kome SmartHome IoT",
        href: "https://iot.kome.top"
    },{
        title: "SvTre",
        href: "https://svtre.com/"
    }
]
